### ISSUE TITLE
Naming: Remove tsb from name

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/tsb-jahresbericht-2021#7]
We all know we are the tsb

**Comment by MRigal** [comment]
Well, there is a jahresbericht for the citylab and one for the tsb, how should we distinguish between them?

**Comment by ff6347** [comment]
True dat. I didn't think about that. We had lots of repos before that had the "tsb" in their name for no reason. Actually we should rename the Citylab repo for that. Since e we still have the org name Technologiestiftung.

**Comment by ff6347** [comment]
We have this one. https://github.com/technologiestiftung/tsb-jahresrueckblick-2021 but is it TSB or Citylab?

**Comment by ff6347** [comment]
Rule of thumb. Repos don't need a tsb in their name since we are technologiestiftung/<repo>

If this creates a naming collision with something from the Citylab IMHO the Citylab one has to be renamed since Citylab is a project

**Comment by ZenVega** [comment]
> We have this one. https://github.com/technologiestiftung/tsb-jahresrueckblick-2021 but is it TSB or Citylab?

That one is from CityLab

**Comment by ff6347** [comment]
I'll rename it next week

**Comment by ZenVega** [comment]
Alright, I'll also rename it then
